Carousel map features
faviru/yard-frontend pull request #11
Opened 2017-07-08 20:45 UTC by faviru

2017-07-08 21:38 UTC, evgenyrodionov commented on src/Complexes/Show/AreaFeatures.jsx
> +import Map from './Map';
резервное слово вообще-то

2017-07-08 21:38 UTC, evgenyrodionov commented
Жду деплоя, завтра распишу всё

2017-07-08 22:13 UTC, imevro requested changes

2017-07-08 22:13 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +    get('/complexes')
и куда фильтр стейт паблик пропал

2017-07-08 22:13 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +  return from || to ?
можно проще

2017-07-08 22:13 UTC, evgenyrodionov commented on src/Complexes/Show/Gallery.jsx
> +function formatPhotosCount(count) {
плюралайзером делается

2017-07-08 22:13 UTC, evgenyrodionov commented on src/Complexes/Show/Map.jsx
> +  accessToken: 'pk.eyJ1IjoianVzdHVzZWJyYWluIiwiYSI6ImNpbHV1dWlmYTAwNmp2Zm02NjZkZmIybGkifQ.feSAgXjbU00mlAjBQyv1lQ',
через энв-параметры

2017-07-08 22:13 UTC, evgenyrodionov commented on src/Complexes/Show/ModalGallery.jsx
> +// @flow
сноси, эта галерея нерабочая

2017-07-08 22:13 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
>          <Features
не проще передать сразу комплекс и внутри это всё доставать?

2017-07-08 22:13 UTC, evgenyrodionov commented on src/Complexes/dictionaries.js
> +export const offerKinds = {
где флоу

2017-07-08 22:13 UTC, evgenyrodionov commented on src/utils.js
> +export function getPublicImageUrl(id: string, height: number = 512): string {
в чем разница функции этой и той что выше

2017-07-09 22:06 UTC, imevro requested changes

2017-07-09 22:06 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
>    from: ?number, to: ?number, units: string, precision: number = 1): string {
поч фром и ту это опциональные поля?

2017-07-09 22:06 UTC, evgenyrodionov commented on src/Complexes/Show/Gallery.jsx
> +import pluralize from 'pluralize-ru';
сделай компонентом, смысл функцию дергать

2017-07-09 22:06 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
>            propertiesCount={propertiesCount}
вопрос в силе — передавай в этот компонент полностью данные по комплексу и внутри все разворачивай и разбирай

2017-07-09 22:31 UTC, faviru commented on src/Complexes/Show/Features.jsx
>    from: ?number, to: ?number, units: string, precision: number = 1): string {
они не опциональные, а намбер или андефайнд

2017-07-09 22:31 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
>    from: ?number, to: ?number, units: string, precision: number = 1): string {
это одно и то же. Как сюда вообще андефайнед может прилететь?

2017-07-09 22:32 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
>    from: ?number, to: ?number, units: string, precision: number = 1): string {
хотя я понял, невермайнд

2017-07-10 09:12 UTC, imevro requested changes

2017-07-10 09:12 UTC, evgenyrodionov commented on src/Complexes/Show/Gallery.jsx
> +              four={'фотографии'}
`2 фотографии` вычисляется через проп `four`?

2017-07-10 09:12 UTC, evgenyrodionov commented on src/Complexes/Show/AreaFeatures.jsx
> +import Map from './Map';
Ну и че?

2017-07-10 09:12 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +          propertiesCount={propertiesCount}
С этим что? В третий раз говорю передавать в компонент данные комплекса и доставать значения внутри, а не передавать список из 20-ти

2017-07-11 09:20 UTC, imevro requested changes

2017-07-11 09:20 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +export function getFormatCeilHeight(from: ?number, to: ?number): string {
гет или формат?

2017-07-11 09:20 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +export function getFormatCeilHeight(from: ?number, to: ?number): string {
get formatted ок
format ок
get format не ок

2017-07-11 09:20 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +        <Features {...(this.state.complex || {})} />
нет, передавай комплекс как проп, потому что тогда неочевидно какие данные уходят в проп

2017-07-11 09:20 UTC, evgenyrodionov commented on src/Complexes/Show/Gallery.jsx
>                one={'фотография'}
тут можно без интерполяции джс-строк

2017-07-11 09:20 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +              <FeatureTitle>Количество квартир</FeatureTitle>
избавься от префикса `Feature`

2017-07-11 09:20 UTC, evgenyrodionov commented on src/Complexes/Show/Features.jsx
> +              <FeatureTitle>Количество квартир</FeatureTitle>
ты и так в файле Features

2017-07-11 17:19 UTC, merged